// import 'package:firebase_core/firebase_core.dart';

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     return const FirebaseOptions(
//       apiKey: 'YOUR_API_KEY',
//       appId: '1:1022309695589:android:5a8b6038d636648629468c',
//       messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
//       projectId: 'YOUR_PROJECT_ID',
//     );
//   }
// }
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBASW5YOOM2s6h8QoaRHXHyXVSqhW4mkY',
    appId: '1:1022309695589:web:4e439cf5ef954d6829468c',
    messagingSenderId: '1022309695589',
    projectId: 'mad-db-1a2d7',
    authDomain: 'mad-db-1a2d7.firebaseapp.com',
    storageBucket: 'mad-db-1a2d7.appspot.com',
    measurementId: 'G-Y7MSQ591Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRziXsN2fpQb2u1mF_7_Rvn-qHXgloUzU',
    appId: '1:1022309695589:android:861d382b18306f0e29468c',
    messagingSenderId: '1022309695589',
    projectId: 'mad-db-1a2d7',
    storageBucket: 'mad-db-1a2d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKDw4J_pBCtU9PoMZ1sYmIZFdCpv9UAg0',
    appId: '1:1022309695589:ios:9d3a301a3f764e5f29468c',
    messagingSenderId: '1022309695589',
    projectId: 'mad-db-1a2d7',
    storageBucket: 'mad-db-1a2d7.appspot.com',
    iosBundleId: 'com.example.moviesearchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqvKp7E1gluCnhG2_94aDPgUN0IZ7vNzs',
    appId: '1:1022309695589:android:5a8b6038d636648629468c',
    messagingSenderId: '1022309695589',
    projectId: 'mad-db-1a2d7',
    storageBucket: 'mad-db-1a2d7.appspot.com',
    iosClientId:
        '1022309695589-4ssal3mi04la06363r9oraiquujpm4je.apps.googleusercontent.com',
    iosBundleId: 'com.example.imdbClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBASW5YOOM2s6h8QoaRHXHyXVSqhW4mkY',
    appId: '1:1022309695589:web:259f92b78a589df529468c',
    messagingSenderId: '1022309695589',
    projectId: 'mad-db-1a2d7',
    authDomain: 'mad-db-1a2d7.firebaseapp.com',
    storageBucket: 'mad-db-1a2d7.appspot.com',
    measurementId: 'G-73QWFCG164',
  );

}